---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule-template-rhel6
    image: registry.access.redhat.com/rhel6:6.9
  - name: molecule-template-rhel7
    image: registry.access.redhat.com/rhel7:7.4
    privileged: True                                         # required for systemd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"                   # required for systemd
    command: /usr/sbin/init                                  # required for systemd
  - name: molecule-template-centos7
    image: centos:7
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: /usr/sbin/init
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
# verifier:
#   name: goss
verifier:
  name: testinfra
  lint:
    name: flake8
